---
- name: Change Hostname
  hosts: all
  become: true
  vars:
    ansible_hostname:
      ansible: ansible
      jenkins: jenkins
      kubernetes: kubernetes
  tasks:
    - name: Change hostname
      hostname:
        name: "{{ ansible_hostname[inventory_hostname] }}"
      register: hostname_changed
    - name: Print changed hostname
      debug:
        var: hostname_changed
