---
- name: Install Appliction for CI/CD pipeline
  hosts: ansible
  become: true

  vars: 
    ansible_user: ansible
    docker_version: "5:20.10.13~3-0~ubuntu-jammy"
    minikube_version: "latest"

  tasks:
    
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true
      when: ansible_hostname == 'ansible'

    - name: Install required packages
      apt:
        pkg: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
      when: ansible_hostname == 'ansible'
    
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_hostname == 'ansible'

    - name: Add Docker APT repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
      when: ansible_hostname == 'ansible'

    - name: Update apt and install Docker CE
      apt:
        name: 
          - docker-ce 
          - docker-ce-cli  
          - containerd.io 
        state: latest
        update_cache: true
      when: ansible_hostname == 'ansible'



    - name: Install Docker Module for Python
      pip:
        name: docker
      when: ansible_hostname == 'ansible'


    - name: Service status - docker
      service:
        name: docker
        state: started
      when: ansible_hostname == 'ansible'


    - name: Add current user to Docker group
      user:
        name: "{{ ansible_user }}"
        append: yes
        groups: docker
      when: ansible_hostname == 'ansible'
